#!/usr/bin/env bash
# OperatorOS PreCompact Hook
# Saves session state BEFORE Claude Code compresses context.
# This is the most important hook — it turns context resets from
# catastrophic information loss into graceful handoffs.
#
# Install: Add to ~/.claude/settings.json under hooks.PreCompact
# Input: JSON on stdin with {cwd, session_id, ...}

set -euo pipefail

INPUT=$(cat)

# --- Find vault ---
CWD=$(echo "$INPUT" | python3 -c "import json,sys; print(json.load(sys.stdin).get('cwd',''))" 2>/dev/null || echo "$HOME")
CLAUDE_PROJECTS="$HOME/.claude/projects"
PROJECT_KEY=$(echo "$CWD" | sed 's|^/||; s|/|-|g')
VAULT_DIR="$CLAUDE_PROJECTS/-${PROJECT_KEY}/memory"

if [ ! -d "$VAULT_DIR" ] 2>/dev/null; then
  for candidate in "$HOME/.claude/memory" "$HOME/.operatoros/vault"; do
    [ -d "$candidate" ] && VAULT_DIR="$candidate" && break
  done
fi

[ ! -d "$VAULT_DIR" ] 2>/dev/null && exit 0

HANDOFF="$VAULT_DIR/ops/session-handoff.md"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
DATE=$(date +%Y-%m-%d)

# --- Capture Paperclip state if available ---
PAPERCLIP_STATE=""
if curl -s --max-time 2 "http://127.0.0.1:3100/api/companies" > /dev/null 2>&1; then
  PAPERCLIP_STATE=$(curl -s --max-time 5 "http://127.0.0.1:3100/api/companies" 2>/dev/null | python3 -c "
import json, sys
try:
    companies = json.load(sys.stdin)
    lines = []
    for c in sorted(companies, key=lambda x: x['spentMonthlyCents'], reverse=True):
        name = c['name']
        prefix = c['issuePrefix']
        spent = c['spentMonthlyCents'] / 100
        counter = c['issueCounter']
        lines.append(f'| {name} | {prefix} | {counter} issues | \${spent:.2f} spent |')
    print('| Company | Prefix | Issues | Spend |')
    print('|---------|--------|--------|-------|')
    print('\n'.join(lines))
except:
    pass
" 2>/dev/null || echo "")
fi

# --- Capture recent git activity ---
GIT_ACTIVITY=""
for repo_dir in "$CWD" "$HOME/openclaw" "$HOME/genesis-tools" "$HOME/operatoros"; do
  if [ -d "$repo_dir/.git" ]; then
    COMMITS=$(cd "$repo_dir" && git log --oneline --since="6 hours ago" 2>/dev/null | head -5)
    if [ -n "$COMMITS" ]; then
      REPO_NAME=$(basename "$repo_dir")
      GIT_ACTIVITY="${GIT_ACTIVITY}\n### ${REPO_NAME}\n\`\`\`\n${COMMITS}\n\`\`\`\n"
    fi
  fi
done

# --- Capture running processes ---
CLAUDE_PROCS=$(ps aux | grep -c "[c]laude.*--model" 2>/dev/null || echo "0")
SERVICE_STATUS=""
for svc in knowledge-server observatory-server genesis-hook-server; do
  if systemctl --user is-active "$svc" > /dev/null 2>&1; then
    SERVICE_STATUS="${SERVICE_STATUS}${svc}: running, "
  else
    SERVICE_STATUS="${SERVICE_STATUS}${svc}: DOWN, "
  fi
done

# --- Write pre-compact snapshot ---
# We APPEND a snapshot section rather than overwriting, so manual content is preserved
SNAPSHOT_MARKER="<!-- PRECOMPACT SNAPSHOT -->"

# Remove old snapshot if exists
if grep -q "$SNAPSHOT_MARKER" "$HANDOFF" 2>/dev/null; then
  sed -i "/$SNAPSHOT_MARKER/,\$d" "$HANDOFF" 2>/dev/null || true
fi

cat >> "$HANDOFF" << SNAPSHOT

$SNAPSHOT_MARKER
## Pre-Compact Snapshot ($TIMESTAMP)

**Context was about to be compressed.** The AI was in the middle of work when this fired.

### System State
- Claude instances running: $CLAUDE_PROCS
- Services: ${SERVICE_STATUS%%, }

### Paperclip Companies
$PAPERCLIP_STATE

### Recent Git Activity
$(echo -e "$GIT_ACTIVITY")

*This snapshot was auto-generated by the PreCompact hook. The AI should read the full handoff above for strategic context.*
SNAPSHOT

echo "[PRECOMPACT] Saved session snapshot to $HANDOFF at $TIMESTAMP" >&2
